run:
	cd round_trip; make all; cd ../;
	cd bandwidth; make all; cd ../;
	cd connection_overhead; make all; cd ../;

clean:
	cd round_trip; make clean; cd ../;
	cd bandwidth; make clean; cd ../;
	cd connection_overhead; make clean; cd ../;